name: Build Container for the container example

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
      - name: Build containers
        run: |
          podman build -f containers/images/Dockerfile -t "containers-example:latest"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push containers
        run: |
          podman tag "containers-example:latest" "ghcr.io/globus-gladier/gladier-client-examples/containers-example:latest"
          podman push "ghcr.io/globus-gladier/gladier-client-examples/containers-example:latest"
